# Generated by Django 5.2.8 on 2025-11-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food & Groceries'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('education', 'Education'), ('health', 'Health & Medical'), ('shopping', 'Shopping'), ('other', 'Other'), ('salary', 'Salary'), ('freelance', 'Freelance'), ('scholarship', 'Scholarship'), ('part-time job', 'Part-time Job'), ('internship', 'Internship'), ('bonus', 'Bonus'), ('investment', 'Investment'), ('gift', 'Gift'), ('allowance', 'Allowance')], help_text='Required for both income and expenses', max_length=50, null=True),
        ),
    ]
